# Generated by Django 4.2.7 on 2023-11-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
        migrations.AddField(
            model_name='transactionproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
