# Generated by Django 4.2.7 on 2023-11-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_myuser_options_alter_myuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], db_column='role', default='user', max_length=20),
        ),
    ]
