# Generated by Django 4.2.7 on 2023-11-28 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_myuser_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='user_role',
            new_name='role',
        ),
    ]
