# Generated by Django 4.2.7 on 2023-11-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_rename_user_role_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('analyst', 'Analyst')], db_column='role', default='user', max_length=20),
        ),
    ]
